print("To form your meal deal please select a main, drink and snack!")
item1 = input("What would you like for your main? ")
item2 = input("What would you like for your drink? ")
item3 = input("What would you like for your snack? ")
print("You have selected the following items to form your meal deal: ")
print(item1)
print(item2)
print(item3)